In [1]:
from matplotlib import pyplot as plt
import datetime
import numpy as np
import pandas as pd
import seaborn as sns

data = pd.read_csv('eplusout.csv')
data_i = pd.DataFrame(data)

# Ajout de l'ann√©e dans la feature de temps
data_i['Date/Time']=data_i['Date/Time'].apply(lambda x :  x.split(' ')[1]+'/2018 '+ x.split(' ')[3])

# S√©paration des donn√©es de date et de temps
data_i['Date'] = data_i['Date/Time'].apply(lambda x :  x.split(' ')[0])
data_i['Time'] = data_i['Date/Time'].apply(lambda x :  x.split(' ')[1])
#data_i['Date/Time'] = pd.to_datetime(data_i['Date/Time'],format='%d/%m/%Y %H:%M:%S', errors = 'coerce')
data_i.head()

,Date/Time,Environment:Site Outdoor Air Drybulb Temperature [C](TimeStep),THERMAL ZONE 2:Zone People Occupant Count [](TimeStep),THERMAL ZONE 1:Zone People Occupant Count [](TimeStep),THERMAL ZONE 1:Zone Air Temperature [C](TimeStep),THERMAL ZONE 1:Zone Air Relative Humidity [%](TimeStep),THERMAL ZONE 1:Zone Thermostat Heating Setpoint Temperature [C](TimeStep),THERMAL ZONE 2:Zone Air Temperature [C](TimeStep),THERMAL ZONE 2:Zone Air Relative Humidity [%](TimeStep),THERMAL ZONE 2:Zone Thermostat Heating Setpoint Temperature [C](TimeStep),Electricity:Facility [J](TimeStep),Date,Time
0,01/01/2018 00:15:00,5.525,0.0,0.0,10.047756,74.226021,0.0,9.815114,75.351337,0.0,489857.142857,01/01/2018,00:15:00
1,01/01/2018 00:30:00,4.650,0.0,0.0,9.663208,72.672872,0.0,9.420467,73.772077,0.0,489857.142857,01/01/2018,00:30:00
2,01/01/2018 00:45:00,3.775,0.0,0.0,9.156076,69.080373,0.0,8.902570,70.149672,0.0,489857.142857,01/01/2018,00:45:00
3,01/01/2018 01:00:00,2.900,0.0,0.0,8.724622,66.087139,0.0,8.462161,67.162583,0.0,489857.142857,01/01/2018,01:00:00
4,01/01/2018 01:15:00,3.250,0.0,0.0,8.637872,64.685458,0.0,8.377323,65.795079,0.0,489857.142857,01/01/2018,01:15:00

In [2]:
# Cr√©ation du mask de s√©paration horaire des Jours/Nuits
mask = (data_i['Time'] > '06:30:00') & (data_i['Time'] <= '18:15:00')
#data_i['Jour/Nuit'] = np.where(mask, 'Jour', 'Nuit')

# Jeu de donn√©es avec une nouvelle colonne Jour/Nuit en nombres
data_m = data_i.copy()
data_m['Jour=0/Nuit=1'] = np.where(mask, 0, 1)

# Suppression des colonnes de cha√Ænes de caract√®res
data_m.pop("Date/Time")
#data_m.pop("Jour/Nuit")
data_m.pop("Date")
data_m.pop("Time")

# Repr√©sentation de la moyenne de chaque colonne selon la p√©riode de la journ√©e
data_m.groupby('Jour=0/Nuit=1').mean()

,Environment:Site Outdoor Air Drybulb Temperature [C](TimeStep),THERMAL ZONE 2:Zone People Occupant Count [](TimeStep),THERMAL ZONE 1:Zone People Occupant Count [](TimeStep),THERMAL ZONE 1:Zone Air Temperature [C](TimeStep),THERMAL ZONE 1:Zone Air Relative Humidity [%](TimeStep),THERMAL ZONE 1:Zone Thermostat Heating Setpoint Temperature [C](TimeStep),THERMAL ZONE 2:Zone Air Temperature [C](TimeStep),THERMAL ZONE 2:Zone Air Relative Humidity [%](TimeStep),THERMAL ZONE 2:Zone Thermostat Heating Setpoint Temperature [C](TimeStep),Electricity:Facility [J](TimeStep)
Jour=0/Nuit=1,,,,,,,,,,
0,4.309231,30.378311,12.729044,18.046426,40.336200,16.223747,15.208751,48.118831,10.114619,8.744346e+06
1,3.457933,0.028345,0.028345,8.809420,64.886541,1.290323,8.581698,65.869331,1.290323,7.185105e+05

In [3]:
# Cr√©ation des jeux de donn√©es s√©par√©s (Jour/Nuit)
data_nuit = data_m[data_m['Jour=0/Nuit=1']==1]
data_jour = data_m[data_m['Jour=0/Nuit=1']==0]
data_nuit.head()

,Environment:Site Outdoor Air Drybulb Temperature [C](TimeStep),THERMAL ZONE 2:Zone People Occupant Count [](TimeStep),THERMAL ZONE 1:Zone People Occupant Count [](TimeStep),THERMAL ZONE 1:Zone Air Temperature [C](TimeStep),THERMAL ZONE 1:Zone Air Relative Humidity [%](TimeStep),THERMAL ZONE 1:Zone Thermostat Heating Setpoint Temperature [C](TimeStep),THERMAL ZONE 2:Zone Air Temperature [C](TimeStep),THERMAL ZONE 2:Zone Air Relative Humidity [%](TimeStep),THERMAL ZONE 2:Zone Thermostat Heating Setpoint Temperature [C](TimeStep),Electricity:Facility [J](TimeStep),Jour=0/Nuit=1
0,5.525,0.0,0.0,10.047756,74.226021,0.0,9.815114,75.351337,0.0,489857.142857,1
1,4.650,0.0,0.0,9.663208,72.672872,0.0,9.420467,73.772077,0.0,489857.142857,1
2,3.775,0.0,0.0,9.156076,69.080373,0.0,8.902570,70.149672,0.0,489857.142857,1
3,2.900,0.0,0.0,8.724622,66.087139,0.0,8.462161,67.162583,0.0,489857.142857,1
4,3.250,0.0,0.0,8.637872,64.685458,0.0,8.377323,65.795079,0.0,489857.142857,1